### ISSUE TITLE
primary_015mm_triggersR1.stl is broken after split and arrange

### ISSUE THREAD

**Issue by iovxw** [inputlabs/alpakka_case#14]
Slicer: PrusaSlicer

Steps to reproduce:

1. Import the primary_015mm_triggersR1.stl:
![image](https://github.com/inputlabs/alpakka_case/assets/6631572/6890a653-d055-4312-b774-dbabfa0ca921)

2. Click Split to objects -> Arrange
![image](https://github.com/inputlabs/alpakka_case/assets/6631572/dd482717-02aa-488e-8fc6-34baca71e3e6)

**Comment by marcos-diaz** [comment]
This should not be an issue anymore since the L1/R1 triggers were ported to Build123d.

Thanks for the report.
