### ISSUE TITLE
Wheel core disconnected hexagonal shaft

### ISSUE THREAD

**Issue by aresgit** [inputlabs/alpakka_case#21]
**Release:** c0.96.0

**Summary:** The STL and STEP files for the wheel core are missing the semi-circular transition connecting the hexagonal shaft.

**Steps to Reproduce:**
1. Download the stl.zip or step.zip file from the [c0.96.0 release download page](https://github.com/inputlabs/alpakka_caTheacseThe/releases/tag/0.96.0)
2. Unzip the downloaded archive file
3. Open the secondary_007mm_wheel_core.stl or secondary_007mm_wheel_core.step file using your favorite slicer or CAD software (screenshots attached)

**Notes**
- STL file opening tested on the following programs:
  - PrusaSlicer 2.7.4
  - Fusion360
  - Tinkercad.com
  - onshape.com
- STEP file opening tested on the following programs:
  - Fusion360
  - onshape.com
- Performing a `make release` of the repo as described in the README results in valid STL and STEP files being produced and they have a different checksum than the wheel core files in the c.0.96.0 stl.zip or step.zip archives.

![Screenshot from 2024-04-27 16-33-44](https://github.com/inputlabs/alpakka_case/assets/11272581/8960897e-9992-4289-a6ce-0dace4031e8f)

![Screenshot from 2024-04-27 21-04-48](https://github.com/inputlabs/alpakka_case/assets/11272581/fbadd455-d516-4d13-80e8-f90499fe99f4)

![Screenshot from 2024-04-27 22-20-47](https://github.com/inputlabs/alpakka_case/assets/11272581/a4db733b-2328-4624-a81d-3044e5f4d654)

**Comment by marcos-diaz** [comment]
Can you please check if this is still an issue in `0.96.1` ? 🙏 
(could be that the export script was doing something funny)

**Comment by aresgit** [comment]
It looks good now! 🎉 👏 

The first image is from Tinkercad and the second is from Fusion360 after importing both the previous (0.96.0) and new (0.96.1) wheel core STL files.

![0 96 0 vs 0 96 1 Tinkercad](https://github.com/inputlabs/alpakka_case/assets/11272581/58008e6a-705f-4a22-8b0b-2ef83f939eb7)

![0 96 0 vs 0 96 1 Fusion360](https://github.com/inputlabs/alpakka_case/assets/11272581/d02ecd2e-0a65-4a72-90f3-fb14fe4cc58c)

Thank you!

**Comment by marcos-diaz** [comment]
Cool, thank you!
