### ISSUE TITLE
Preview images are broken on the ReadMe.

### ISSUE THREAD

**Issue by SecularSteve** [inputlabs/alpakka_case#5]
Just so you know...

**Comment by przymi** [comment]
They appear to work fine in GH. Of course those are relative, but if you checkout the entire repository, you should get the preview images as well.  Where are you viewing the readme?

**Comment by SecularSteve** [comment]
Android App

**Comment by przymi** [comment]
You are right. Thank you for bringing this to our attention. I tried it with the GH Android app and it would appear to be a big in how the client deals with the GH-specific way of embedding images.
I informed the developer of the GH Android client accordingly.
May may address this in the form of a work-around at a later stage.

**Comment by SecularSteve** [comment]
Good to know that it's an app-only issue.

I just tried it in the (mobile) browser, and it works without issues.

The mobile app is just one problem after another. At this point I'd personally just recommend to Bookmark GH in your mobile browser. It's a ton better.

Thank you for your response regardless, good luck 🍀, and have a nice day 👍
